--
-- Name: contract_summary; Type: TABLE; Schema: -; Owner: -
--

CREATE TABLE IF NOT EXISTS contract_summary (
    contract_id varchar PRIMARY KEY,
    product_name varchar,
    contract_number varchar,
    cusip varchar,
    carrier varchar,
    status varchar,
    plan_type varchar,
    type varchar,
    active boolean,
    state varchar,
    mva boolean,
    carrier_firm varchar,
    broker varchar,
    product_type varchar,
    life_term_duration integer,
    is_advisory boolean,
    account_guaranteed_death_benefit boolean,
    withdrawals_taken boolean,
    account_income_benefit_base boolean,
    rmd_taken boolean,
    account_value numeric,
    surrender_value numeric,
    face_value_amount numeric,
    cash_value numeric,
    net_cash_surrender_value numeric,
    total_premium_paid numeric,
    issue_date date,
    cdsc_end_date date,
    maturity_date date,
    rep_name varchar,
    rep_npns varchar[],
    rep_crds varchar[],
    owner_name varchar,
    insured_name varchar,
    annuitant_name varchar,
    owner_address varchar,
    owner_city varchar,
    owner_state varchar,
    owner_postal_code varchar,
    owner_country_code varchar,
    annuitant_age integer,
    owner_age integer,
    insured_age integer,
    next_event_date date,
    event_amount numeric,
    beneficiary_names varchar[],
    beneficiary_names_display text,
    out_of_surrender boolean,
    maturity boolean,
    anniversary boolean,
    rate_renewal boolean,
    exchange_opportunity boolean
);
