# generated by datamodel-codegen:
#   filename:  sureify.yaml
#   timestamp: 2026-02-26T02:23:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class SuitabilityStatus(Enum):
    complete = 'complete'
    incomplete = 'incomplete'
    not_started = 'not-started'


class EligibilityStatus(Enum):
    eligible = 'eligible'
    restricted = 'restricted'
    ineligible = 'ineligible'


class Type(Enum):
    feature = 'feature'
    benefit = 'benefit'
    rider = 'rider'
    limitation = 'limitation'


class PolicyFeature(BaseModel):
    name: str = Field(
        ...,
        description='Display name of the feature.',
        examples=['Nursing Home Waiver'],
    )
    description: str = Field(
        ...,
        description='Explanation of the feature, its terms, and conditions.',
        examples=['Surrender charges waived after 90-day qualifying stay'],
    )
    included: bool = Field(
        ...,
        description='Whether this feature is currently active and in effect on the policy.',
    )
    type: Type = Field(
        ...,
        description='Classification of the item. "feature": a standard contract\nprovision included at no additional cost (e.g., tax-deferred growth,\nnursing home waiver). "benefit": a contractual guarantee provided\nby the policy (e.g., guaranteed minimum rate, death benefit).\n"rider": an optional add-on provision that may carry additional\ncost or conditions (e.g., guaranteed lifetime withdrawal benefit,\nenhanced death benefit). "limitation": a contractual restriction\nor penalty that constrains the policyholder (e.g., market value\nadjustment, early withdrawal penalty, surrender charge schedule).\n',
    )


class ProductOption(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    productId: str = Field(
        ...,
        description='Business identifier that correlates this option with a visualization product.',
        examples=['PROD-FLEXGROWTH-P-7'],
    )
    name: str = Field(
        ..., description='Product marketing name.', examples=['FlexGrowth Plus MYGA']
    )
    carrier: str = Field(
        ..., description='Issuing insurance carrier.', examples=['Great American']
    )
    rate: str = Field(
        ...,
        description='The annualized interest rate credited to new contracts issued under this product today.',
        examples=['4.25%'],
    )
    term: str = Field(
        ...,
        description='The length of the initial rate guarantee period. During this\nperiod the credited rate is locked in and cannot be reduced by\nthe carrier. At the end of the term the carrier declares a new\nrate (subject to the guaranteedMinRate floor).\n',
        examples=['7 years'],
    )
    premiumBonus: str | None = Field(
        None,
        description='A one-time bonus the carrier adds to the contract value when the\ninitial premium is deposited, expressed as a percentage of the\npremium. Premium bonuses typically vest gradually over the\nsurrender period — if the contract is surrendered early, the\nunvested portion of the bonus is forfeited. Null if the product\ndoes not offer a premium bonus.\n',
        examples=['3.0%'],
    )
    surrenderPeriod: str = Field(
        ...,
        description='The number of years from contract issue during which surrender\ncharges apply. During this period, fully cashing out the contract\nincurs a penalty. After the surrender period expires, the full\naccumulated value is available without charge.\n',
        examples=['7'],
    )
    surrenderCharge: str | None = Field(
        None,
        description='The surrender charge schedule for this product, showing the\ninitial charge percentage and how it declines over time. Surrender\ncharges are deducted from the contract value if the policy is\nfully surrendered during the surrender period.\n',
        examples=['7% (declining 1% annually)'],
    )
    freeWithdrawal: str = Field(
        ...,
        description='The percentage of the contract value the holder may withdraw each\nyear without triggering a surrender charge, even during the\nsurrender period.\n',
        examples=['10%'],
    )
    deathBenefit: str = Field(
        ...,
        description='The death benefit provision of the product. "Standard" means\nbeneficiaries receive the accumulated contract value at time of\ndeath. "Enhanced" means beneficiaries receive the greater of the\naccumulated value or a formula-based amount (such as return of\npremium plus credited interest), providing a floor on the death\nbenefit.\n',
        examples=['Enhanced -- return of premium plus interest'],
    )
    guaranteedMinRate: str = Field(
        ...,
        description='The contractual floor rate for this product — the lowest rate the\ncarrier can ever credit, regardless of market conditions. This\nguarantee applies for the life of the contract, including all\nrenewal periods after the initial term.\n',
        examples=['2.50%'],
    )
    riders: list[str] | None = Field(
        None,
        description='Optional rider provisions available with this product. Riders are\nadd-on contract features that provide additional guarantees or\nprotections beyond the base contract (e.g., guaranteed lifetime\nincome, nursing home charge waivers, enhanced death benefits).\n',
        examples=[
            [
                'Guaranteed Lifetime Withdrawal Benefit',
                'Nursing Home Confinement Waiver',
            ]
        ],
    )
    features: list[str] | None = Field(
        None,
        description='Standard product features included in the base contract at no additional cost.',
        examples=[['Tax-deferred accumulation', 'Penalty-free systematic withdrawals']],
    )
    liquidity: str | None = Field(
        None,
        description="Summary of the product's liquidity provisions — how and when the\ncontract holder can access funds, including the free withdrawal\nallowance during the surrender period and full access after the\nsurrender period ends.\n",
        examples=['10% annual free withdrawal; full liquidity after surrender period'],
    )
    mvaPenalty: str | None = Field(
        None,
        description='Whether this product includes a market value adjustment (MVA)\nprovision. An MVA adjusts the surrender value based on changes in\nprevailing interest rates since the contract was issued. When\nrates have risen since issue, the MVA reduces the surrender value;\nwhen rates have fallen, it may increase the surrender value. Null\nif the product does not include an MVA provision.\n',
        examples=['Subject to MVA during surrender period'],
    )
    licensingApproved: bool | None = Field(
        None,
        description='Whether the requesting advisor currently holds the required\ninsurance licenses and carrier appointment to sell this product.\nFalse means the advisor cannot submit business for this product\nuntil licensing and appointment are completed.\n',
    )
    licensingDetails: str | None = Field(
        None,
        description="Additional context about the advisor's licensing status for this\nproduct. When licensingApproved is false, this field typically\ndescribes what action is needed to obtain approval (e.g., carrier\nappointment application, state licensing requirement). Null when\nno additional detail is available.\n",
        examples=['Appointment with carrier required -- apply at carrier portal'],
    )


class ResidesInNursingHome(Enum):
    yes = 'yes'
    no = 'no'


class HasLongTermCareInsurance(Enum):
    yes = 'yes'
    no = 'no'


class HasMedicareSupplemental(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateExpenseIncrease(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateIncomeDecrease(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateLiquidAssetDecrease(Enum):
    yes = 'yes'
    no = 'no'


class ApplyToMeansTestedBenefits(Enum):
    yes = 'yes'
    no = 'no'


class ComparisonParameters(BaseModel):
    residesInNursingHome: ResidesInNursingHome | None = Field(
        None,
        description='Whether the client currently resides in a nursing home or\nlong-term care facility. Many annuity contracts include nursing\nhome waiver provisions that alter surrender charge terms for\npolicyholders in qualifying care facilities.\n',
    )
    hasLongTermCareInsurance: HasLongTermCareInsurance | None = Field(
        None,
        description='Whether the client has a separate long-term care insurance policy covering extended care costs.',
    )
    hasMedicareSupplemental: HasMedicareSupplemental | None = Field(
        None,
        description='Whether the client has a Medicare supplemental (Medigap) policy covering costs not paid by Medicare.',
    )
    grossIncome: str | None = Field(
        None, description='Annual gross income.', examples=['85000']
    )
    disposableIncome: str | None = Field(
        None,
        description='Annual disposable income after essential expenses and taxes.',
        examples=['45000'],
    )
    taxBracket: str | None = Field(
        None, description='Current federal income tax bracket.', examples=['22%']
    )
    householdLiquidAssets: str | None = Field(
        None,
        description='Total household liquid assets — cash, savings, money market\naccounts, and other holdings that can be converted to cash\nquickly without significant loss of value. Does not include\nretirement accounts, real estate, or annuity contract values.\n',
        examples=['250000'],
    )
    monthlyLivingExpenses: str | None = Field(
        None,
        description='Average total monthly household living expenses including housing, food, healthcare, insurance, and discretionary spending.',
        examples=['4500'],
    )
    totalAnnuityValue: str | None = Field(
        None,
        description="The combined current value of all annuity contracts the client\nholds, across all carriers. This is the sum of the currentValue\nfields from the client's policyData records.\n",
        examples=['180000'],
    )
    householdNetWorth: str | None = Field(
        None,
        description='Total household net worth — all assets (real estate, investments,\nretirement accounts, liquid assets, annuities) minus all\nliabilities (mortgages, loans, debts).\n',
        examples=['650000'],
    )
    anticipateExpenseIncrease: AnticipateExpenseIncrease | None = Field(
        None,
        description='Whether the client anticipates a significant increase in living\nexpenses in the foreseeable future (e.g., medical costs, dependent\ncare, planned major purchases).\n',
    )
    anticipateIncomeDecrease: AnticipateIncomeDecrease | None = Field(
        None,
        description="Whether the client anticipates a decrease in income in the\nforeseeable future (e.g., upcoming retirement, reduction in\nwork hours, loss of a spouse's income).\n",
    )
    anticipateLiquidAssetDecrease: AnticipateLiquidAssetDecrease | None = Field(
        None,
        description='Whether the client anticipates a significant decrease in liquid\nassets in the foreseeable future (e.g., planned large expenditure,\ngifting, debt payoff).\n',
    )
    financialObjectives: str | None = Field(
        None,
        description="Client's stated financial goals and objectives.",
        examples=[
            'Supplement Social Security with guaranteed income; preserve assets for estate'
        ],
    )
    distributionPlan: str | None = Field(
        None,
        description="The client's planned strategy for taking distributions\n(withdrawals) from their annuity holdings — when they plan to\nstart, how frequently, and in what form (systematic, lump sum,\nRMD-only, etc.).\n",
        examples=['Systematic withdrawals beginning at age 67'],
    )
    ownedAssets: str | None = Field(
        None,
        description="A free-text summary of the client's major asset holdings outside\nof liquid assets, including real estate, retirement accounts,\nexisting annuities, and other investments. This is a self-reported\noverview, not an exhaustive inventory.\n",
        examples=[
            'Primary residence (paid off), 401(k), Roth IRA, existing fixed annuity'
        ],
    )
    timeToFirstDistribution: str | None = Field(
        None,
        description='How long the client expects to wait before taking the first\nwithdrawal from their annuity. "Immediate" indicates the client\nneeds to begin withdrawals now or very soon.\n',
        examples=['5 years'],
    )
    expectedHoldingPeriod: str | None = Field(
        None,
        description='The total length of time the client expects to keep their annuity\ncontract in force before fully surrendering or annuitizing.\n',
        examples=['10+ years'],
    )
    sourceOfFunds: str | None = Field(
        None,
        description='Where the money for the annuity purchase originates. Common\nsources include 1035 exchanges from existing annuity or life\ninsurance contracts, rollovers from employer retirement plans,\nsavings, CD maturities, inheritance, or asset sales. The source\ndetermines the applicable tax treatment and transfer mechanism.\n',
        examples=['1035 exchange from existing annuity and savings account'],
    )
    employmentStatus: str | None = Field(
        None,
        description="The client's current employment situation and, if applicable,\ntheir retirement timeline. Includes whether they are currently\nworking, retired, semi-retired, or self-employed, and when they\nplan to stop working.\n",
        examples=['Employed full-time, plans to retire in 5 years'],
    )
    applyToMeansTestedBenefits: ApplyToMeansTestedBenefits | None = Field(
        None,
        description='Whether the client expects to apply for government benefits that\nare subject to means testing (e.g., Medicaid, Supplemental\nSecurity Income). Annuity holdings and income can affect\neligibility for means-tested programs depending on the state\nand program rules.\n',
    )
    dateOfBirth: str | None = Field(
        None,
        description="The client's date of birth in MM/DD/YYYY format. Age is relevant\nto IRS early withdrawal penalties (which apply before age 59 1/2),\nrequired minimum distribution (RMD) rules (which begin at age 73),\nand maximum issue age limits on certain products.\n",
        examples=['04/12/1960'],
    )


class SuitabilityInlineData(BaseModel):
    clientObjectives: str = Field(
        ...,
        description="The client's stated financial goals and objectives in their own words — what they want to achieve with their investments and retirement planning.",
    )
    riskTolerance: str = Field(
        ...,
        description='The client\'s self-assessed comfort level with investment risk,\nranging from "Conservative" (prioritizes principal protection)\nthrough "Moderate" to "Moderately Aggressive" (willing to accept\nsome variability for higher potential returns).\n',
    )
    timeHorizon: str = Field(
        ...,
        description='The length of time the client expects to keep funds invested\nbefore needing to access them. Expressed as a range (e.g.,\n"3-5 years", "10-15 years", "15+ years").\n',
    )
    liquidityNeeds: str = Field(
        ...,
        description="An assessment of the client's need for accessible funds outside\nof their annuity holdings, including the size of their emergency\nreserves and any anticipated near-term cash needs.\n",
    )
    taxConsiderations: str = Field(
        ...,
        description="A summary of the client's current tax situation and how it may\nchange — their current tax bracket, expected future bracket\n(e.g., if retiring), and the relative value of tax deferral\ngiven their circumstances.\n",
    )
    guaranteedIncome: str = Field(
        ...,
        description="The client's stated preferences around guaranteed income — whether\nthey need a guaranteed income stream, how much per month, when\nit should start, and what it needs to cover (e.g., supplementing\nSocial Security, replacing salary).\n",
    )
    rateExpectations: str = Field(
        ...,
        description="The client's preferences regarding interest rates and returns —\nwhether they prioritize the highest current rate, a longer rate\nguarantee period, a minimum floor rate, or a specific rate\nimprovement threshold over their current holdings.\n",
    )
    surrenderTimeline: str = Field(
        ...,
        description='Whether and when the client anticipates needing to surrender\n(cash out) any annuity contracts. Indicates willingness to\ncommit to a new surrender period.\n',
    )
    livingBenefits: list[str] = Field(
        ...,
        description='Insurance benefit provisions that are important to the client\nand that pay out while the policyholder is still living (as\nopposed to death benefits). Examples include nursing home\nwaivers (surrender charges waived during qualifying care stays),\nterminal illness benefits (early access to funds upon terminal\ndiagnosis), guaranteed lifetime withdrawal benefits (income\npayments guaranteed for life), and disability waivers.\n',
    )


class AssetType(Enum):
    CD = 'CD'
    money_market = 'money-market'
    savings = 'savings'
    field_401k = '401k'
    ira_traditional = 'ira-traditional'
    ira_roth = 'ira-roth'
    brokerage = 'brokerage'
    pension = 'pension'


class LiquidityStatus(Enum):
    liquid = 'liquid'
    locked = 'locked'
    restricted = 'restricted'


class ClientAsset(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    clientId: str = Field(
        ...,
        description='Business identifier for the client who owns this asset.',
        examples=['CLT-2024-00100'],
    )
    assetType: AssetType = Field(
        ...,
        description='Classification of the asset. CD: certificate of deposit with a fixed\nterm and rate. money-market: money market deposit or fund account.\nsavings: bank savings or high-yield savings account. 401k: employer-\nsponsored defined-contribution retirement plan. ira-traditional:\nindividual retirement account funded with pre-tax contributions.\nira-roth: individual retirement account funded with after-tax\ncontributions (qualified withdrawals are tax-free). brokerage:\ntaxable investment/brokerage account. pension: defined-benefit\npension or pension distribution entitlement.\n',
    )
    description: str = Field(
        ...,
        description='Human-readable summary of the asset including term length, institution, or account origin where relevant.',
        examples=['12-month CD at First National Bank'],
    )
    currentValue: str = Field(
        ...,
        description='Current account balance or market value, formatted as USD with currency symbol.',
        examples=['$85,000'],
    )
    interestRate: str | None = Field(
        None,
        description='The annual interest rate or yield currently credited to the asset.\nPresent for rate-bearing instruments (CDs, savings, money market).\nNull for assets where a single credited rate does not apply (retirement\naccounts, brokerage, pension).\n',
        examples=['2.10%'],
    )
    maturityDate: str | None = Field(
        None,
        description="The date the asset's current term ends, in MM/DD/YYYY format. Applies\nto fixed-term instruments such as CDs. On or after this date, the\nprincipal is no longer locked and the holder must decide whether to\nrenew, withdraw, or reallocate the funds. Null for assets with no\nfixed term.\n",
        examples=['04/15/2026'],
    )
    institution: str = Field(
        ...,
        description='The bank, brokerage, or financial institution where the asset is held or administered.',
        examples=['First National Bank'],
    )
    taxQualified: bool = Field(
        ...,
        description='True if the asset is held in a tax-advantaged account (401k,\ntraditional IRA, Roth IRA, qualified pension). False for after-tax\naccounts (savings, CDs, money market, brokerage). Tax qualification\ndetermines the applicable transfer mechanism and tax treatment when\nfunds are moved between financial products.\n',
    )
    liquidityStatus: LiquidityStatus = Field(
        ...,
        description='Indicates how readily the funds can be accessed. "liquid": funds can\nbe withdrawn or transferred without penalty or restriction.\n"locked": funds are committed for a fixed term and early withdrawal\nwould incur a penalty (e.g., a CD before maturity). "restricted":\nfunds are subject to regulatory, plan, or custodial restrictions on\nwithdrawal or transfer (e.g., an active 401k with a current or\nformer employer that requires a qualifying event for distribution).\n',
    )


class PolicyFeaturesData(BaseModel):
    surrenderCharge: str | None = Field(
        None,
        description='The penalty percentage that would be deducted from the contract\nvalue if the policy is surrendered (fully cashed out) today,\nalong with the current position in the declining schedule.\nSurrender charges typically start high and decline annually to\nzero over the surrender period. Null when the surrender charge\nperiod has expired and no penalty applies.\n',
        examples=['2.5% (Year 7 of 10)'],
    )
    withdrawalAllowance: str | None = Field(
        None,
        description='The portion of the contract value the client may withdraw each\nyear without incurring a surrender charge. Withdrawals within\nthis allowance do not trigger penalties even during the surrender\ncharge period.\n',
        examples=['10% annually penalty-free'],
    )
    mvaPenalty: str | None = Field(
        None,
        description='The market value adjustment (MVA) that would apply if the policy\nwere surrendered today. An MVA is a contract provision that adjusts\nthe surrender value up or down based on changes in interest rates\nsince the contract was issued. A negative MVA reduces the surrender\nvalue; a positive MVA increases it. Null when the contract does not\ninclude an MVA provision or the surrender charge period has expired.\n',
        examples=['-3.8% if surrendered today'],
    )
    rateGuarantee: str | None = Field(
        None,
        description='The remaining time until the current credited rate expires and a\nnew rate is declared. During the guarantee period, the carrier\ncannot change the credited rate. Null when the original rate\nguarantee period has expired and the contract is in a renewal\nperiod.\n',
        examples=['5 years remaining'],
    )
    features: list[PolicyFeature] | None = Field(
        None, description='Product features included with the contract.'
    )
    benefits: list[PolicyFeature] | None = Field(
        None, description='Contractual benefits provided by the policy.'
    )
    riders: list[PolicyFeature] | None = Field(
        None, description='Optional riders attached to the policy.'
    )
    limitations: list[PolicyFeature] | None = Field(
        None, description='Contractual restrictions and limitations.'
    )


class ClientProfile(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    clientId: str = Field(
        ...,
        description='Business identifier for the client.',
        examples=['CLT-2024-00412'],
    )
    clientName: str = Field(
        ..., description='Full name of the client.', examples=['Margaret A. Whitfield']
    )
    parameters: ComparisonParameters
    suitability: SuitabilityInlineData | None = Field(
        None, description='Suitability assessment data for this client, if available.'
    )


class PolicyData(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    clientId: str = Field(
        ...,
        description='Business identifier for the client who owns this policy.',
        examples=['CLT-2024-00100'],
    )
    contractId: str = Field(
        ...,
        description='Carrier-assigned contract or policy number.',
        examples=['ANN-2020-5621'],
    )
    clientName: str = Field(
        ...,
        description='Full name of the policy owner.',
        examples=['Margaret A. Whitfield'],
    )
    carrier: str = Field(
        ...,
        description='Issuing insurance carrier.',
        examples=['Integrity Life Insurance'],
    )
    productName: str = Field(
        ...,
        description='Name of the annuity product.',
        examples=['SecureChoice Multi-Year Guarantee Annuity'],
    )
    issueDate: str = Field(
        ...,
        description='Date the contract was originally issued, in MM/DD/YYYY format. Together with the product term, this determines how far the contract is into its surrender charge schedule.',
        examples=['03/15/2018'],
    )
    currentValue: str = Field(
        ...,
        description='Current accumulated contract value (principal plus all credited interest), formatted as USD with currency symbol.',
        examples=['$180,000'],
    )
    surrenderValue: str = Field(
        ...,
        description='The amount the client would receive if they surrendered (cashed out)\nthe contract today. This is the currentValue minus any applicable\nsurrender charges and market value adjustments. The difference\nbetween currentValue and surrenderValue represents the cost of\nexiting the contract at this point in time.\n',
        examples=['$176,400'],
    )
    currentRate: str = Field(
        ...,
        description='The annualized interest rate the carrier is currently crediting on this contract. This is the rate in effect today.',
        examples=['3.80%'],
    )
    renewalRate: str = Field(
        ...,
        description="The interest rate the carrier has declared for the next renewal\nperiod. This is the rate that will take effect on renewalDate,\nreplacing the currentRate. Comparing renewalRate to currentRate\nshows whether the client's credited rate is increasing, decreasing,\nor staying the same at renewal.\n",
        examples=['1.50%'],
    )
    guaranteedMinRate: str = Field(
        ...,
        description='The contractual floor rate — the lowest interest rate the carrier\ncan ever credit on this contract, regardless of market conditions.\nThis rate is guaranteed for the life of the contract.\n',
        examples=['1.50%'],
    )
    renewalDate: str = Field(
        ...,
        description='The date (MM/DD/YYYY) when the current rate guarantee period ends\nand the renewalRate takes effect. After this date the contract\nenters a new rate period.\n',
        examples=['03/15/2026'],
    )
    isMinRateRenewal: bool = Field(
        ...,
        description='True when the renewalRate equals the guaranteedMinRate — meaning\nthe carrier is renewing the contract at the lowest rate the contract\nallows. False when the renewal rate is above the contractual floor.\n',
    )
    suitabilityStatus: SuitabilityStatus = Field(
        ...,
        description='State of the regulatory suitability review for this policy.\n"complete": all required suitability information has been gathered\nand reviewed. "incomplete": suitability review has been started but\nrequired information is still missing. "not-started": no suitability\nreview has been initiated for this policy. A completed suitability\nreview is a regulatory prerequisite before any exchange or\nreplacement transaction can proceed.\n',
    )
    eligibilityStatus: EligibilityStatus = Field(
        ...,
        description='Whether this policy is eligible for exchange or replacement activity.\n"eligible": the policy can be exchanged or replaced under current\nrules. "restricted": the policy has conditions that limit exchange\nactivity (e.g., outstanding loans, pending transactions, or\nregulatory holds). "ineligible": the policy cannot be exchanged\nor replaced at this time.\n',
    )
    features: PolicyFeaturesData
