# generated by datamodel-codegen:
#   filename:  sureify.yaml
#   timestamp: 2026-02-25T20:34:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, conint


class SuitabilityStatus(Enum):
    complete = 'complete'
    incomplete = 'incomplete'
    not_started = 'not-started'


class EligibilityStatus(Enum):
    eligible = 'eligible'
    restricted = 'restricted'
    ineligible = 'ineligible'


class Type(Enum):
    feature = 'feature'
    benefit = 'benefit'
    rider = 'rider'
    limitation = 'limitation'


class PolicyFeature(BaseModel):
    name: str = Field(
        ...,
        description='Display name of the feature.',
        examples=['Nursing Home Waiver'],
    )
    description: str = Field(
        ...,
        description='Explanation of the feature and its terms.',
        examples=['Surrender charges waived after 90-day qualifying stay'],
    )
    included: bool = Field(
        ..., description='Whether this feature is active on the policy.'
    )
    type: Type = Field(..., description='Classification of the feature.')


class SuitabilityData(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    clientId: str = Field(
        ...,
        description='Business identifier for the client this suitability assessment belongs to.',
        examples=['CLT-2024-00100'],
    )
    clientObjectives: str = Field(
        ...,
        description="Summary of the client's stated financial objectives.",
        examples=[
            'Preserve principal with modest growth; generate guaranteed retirement income starting in 5 years'
        ],
    )
    riskTolerance: str = Field(
        ...,
        description="Client's self-assessed risk tolerance level.",
        examples=['Conservative'],
    )
    timeHorizon: str = Field(
        ..., description='Expected investment time horizon.', examples=['5-10 years']
    )
    liquidityNeeds: str = Field(
        ...,
        description="Assessment of the client's need for accessible funds.",
        examples=['Low -- has separate emergency fund covering 12 months of expenses'],
    )
    taxConsiderations: str = Field(
        ...,
        description='Relevant tax situation and planning considerations.',
        examples=['Currently in 22% bracket; expects 12% bracket in retirement'],
    )
    guaranteedIncome: str = Field(
        ...,
        description="Client's desired guaranteed income provisions.",
        examples=[
            'Desires guaranteed income floor of $2,000/month to supplement Social Security'
        ],
    )
    rateExpectations: str = Field(
        ...,
        description="Client's rate and return expectations or preferences.",
        examples=[
            'Willing to accept lower current rate for longer rate guarantee period'
        ],
    )
    surrenderTimeline: str = Field(
        ...,
        description='Whether or when the client anticipates surrendering the contract.',
        examples=['No anticipated need to surrender within the next 7 years'],
    )
    livingBenefits: list[str] = Field(
        ...,
        description='Living benefit features important to the client.',
        examples=[
            [
                'Nursing home waiver',
                'Terminal illness benefit',
                'Guaranteed lifetime withdrawal',
            ]
        ],
    )
    advisorEligibility: str | None = Field(
        None,
        description='Advisor licensing and appointment status relevant to the assessment.',
    )
    score: int | None = Field(None, description='Composite suitability score (0-100).')
    isPrefilled: bool | None = Field(
        None, description='Whether the assessment was pre-populated from existing data.'
    )


class DisclosureItem(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    disclosureId: str = Field(
        ...,
        description='Business identifier for the disclosure document.',
        examples=['DISC-MYGA-001'],
    )
    label: str | None = Field(
        None,
        description='Short label used for display in lists and navigation.',
        examples=['Rate Guarantee'],
    )
    title: str | None = Field(
        None,
        description='Full title of the disclosure document.',
        examples=['Multi-Year Rate Guarantee Disclosure'],
    )
    description: str | None = Field(
        None,
        description='Summary of what the disclosure covers and why it is relevant.',
        examples=[
            'Explains the guaranteed interest rate period and conditions under which the rate may change at renewal.'
        ],
    )
    documentName: str | None = Field(
        None,
        description='Filename of the associated document.',
        examples=['MYGA_Rate_Guarantee_Disclosure_2025.pdf'],
    )
    required: bool = Field(
        ...,
        description='Whether the client must acknowledge this disclosure before proceeding.',
    )
    link: str | None = Field(
        None,
        description='URL where the full disclosure document can be retrieved.',
        examples=[
            'https://docs.example.com/disclosures/MYGA_Rate_Guarantee_Disclosure_2025.pdf'
        ],
    )


class ProductOption(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    productId: str = Field(
        ...,
        description='Business identifier that correlates this option with a visualization product.',
        examples=['PROD-FLEXGROWTH-P-7'],
    )
    name: str = Field(
        ..., description='Product marketing name.', examples=['FlexGrowth Plus MYGA']
    )
    carrier: str = Field(
        ..., description='Issuing insurance carrier.', examples=['Great American']
    )
    rate: str = Field(
        ..., description='Current credited interest rate.', examples=['4.25%']
    )
    term: str = Field(
        ..., description='Rate guarantee term length.', examples=['7 years']
    )
    premiumBonus: str | None = Field(
        None,
        description='First-year premium bonus percentage, if offered.',
        examples=['3.0%'],
    )
    surrenderPeriod: str = Field(
        ...,
        description='Number of years the surrender charge schedule applies.',
        examples=['7'],
    )
    surrenderCharge: str | None = Field(
        None,
        description='Current surrender charge schedule.',
        examples=['7% (declining 1% annually)'],
    )
    freeWithdrawal: str = Field(
        ..., description='Annual penalty-free withdrawal percentage.', examples=['10%']
    )
    deathBenefit: str = Field(
        ...,
        description='Type of death benefit provided.',
        examples=['Enhanced -- return of premium plus interest'],
    )
    guaranteedMinRate: str = Field(
        ...,
        description='Contractual guaranteed minimum interest rate.',
        examples=['2.50%'],
    )
    riders: list[str] | None = Field(
        None,
        description='Optional riders available or attached.',
        examples=[
            [
                'Guaranteed Lifetime Withdrawal Benefit',
                'Nursing Home Confinement Waiver',
            ]
        ],
    )
    features: list[str] | None = Field(
        None,
        description='Included product features.',
        examples=[['Tax-deferred accumulation', 'Penalty-free systematic withdrawals']],
    )
    liquidity: str | None = Field(
        None,
        description="Summary of the product's liquidity provisions.",
        examples=['10% annual free withdrawal; full liquidity after surrender period'],
    )
    mvaPenalty: str | None = Field(
        None,
        description='Whether the product is subject to a market value adjustment.',
        examples=['Subject to MVA during surrender period'],
    )
    licensingApproved: bool | None = Field(
        None,
        description='Whether the requesting advisor is licensed and appointed to sell this product.',
    )
    licensingDetails: str | None = Field(
        None,
        description='Additional licensing status details or required actions.',
        examples=['Appointment with carrier required -- apply at carrier portal'],
    )


class ProjectedRate(BaseModel):
    year: int = Field(..., description='Contract year.', examples=[5])
    conservativeRate: float = Field(
        ..., description='Conservative (floor) rate projection.', examples=[2.5]
    )
    expectedRate: float = Field(
        ..., description='Expected (base case) rate projection.', examples=[3.4]
    )
    optimisticRate: float = Field(
        ..., description='Optimistic (upside) rate projection.', examples=[4.8]
    )


class PerformanceDataPoint(BaseModel):
    year: int = Field(..., description='Contract year.', examples=[7])
    value: float = Field(
        ...,
        description='Projected account value at the end of the year.',
        examples=[148910.25],
    )
    income: float | None = Field(
        None,
        description='Projected income distributed during the year, if applicable.',
        examples=[5400.0],
    )


class Category(Enum):
    surrender = 'surrender'
    bonus = 'bonus'
    rider = 'rider'
    guarantee = 'guarantee'


class VisualizationFeature(BaseModel):
    name: str = Field(
        ...,
        description='Display name of the feature.',
        examples=['Surrender Charge Period'],
    )
    startYear: int = Field(
        ..., description='Contract year the feature begins.', examples=[1]
    )
    endYear: int = Field(
        ..., description='Contract year the feature ends.', examples=[7]
    )
    category: Category = Field(
        ..., description='Classification for grouping and color-coding.'
    )


class ResidesInNursingHome(Enum):
    yes = 'yes'
    no = 'no'


class HasLongTermCareInsurance(Enum):
    yes = 'yes'
    no = 'no'


class HasMedicareSupplemental(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateExpenseIncrease(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateIncomeDecrease(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateLiquidAssetDecrease(Enum):
    yes = 'yes'
    no = 'no'


class ApplyToMeansTestedBenefits(Enum):
    yes = 'yes'
    no = 'no'


class ComparisonParameters(BaseModel):
    residesInNursingHome: ResidesInNursingHome | None = Field(
        None, description='Whether the client currently resides in a nursing home.'
    )
    hasLongTermCareInsurance: HasLongTermCareInsurance | None = Field(
        None, description='Whether the client has long-term care insurance.'
    )
    hasMedicareSupplemental: HasMedicareSupplemental | None = Field(
        None, description='Whether the client has Medicare supplemental coverage.'
    )
    grossIncome: str | None = Field(
        None, description='Annual gross income.', examples=['85000']
    )
    disposableIncome: str | None = Field(
        None,
        description='Annual disposable income after essential expenses and taxes.',
        examples=['45000'],
    )
    taxBracket: str | None = Field(
        None, description='Current federal income tax bracket.', examples=['22%']
    )
    householdLiquidAssets: str | None = Field(
        None,
        description='Total liquid assets (cash, savings, money market).',
        examples=['250000'],
    )
    monthlyLivingExpenses: str | None = Field(
        None, description='Average monthly living expenses.', examples=['4500']
    )
    totalAnnuityValue: str | None = Field(
        None,
        description='Total value of all annuity contracts held.',
        examples=['180000'],
    )
    householdNetWorth: str | None = Field(
        None, description='Total household net worth.', examples=['650000']
    )
    anticipateExpenseIncrease: AnticipateExpenseIncrease | None = Field(
        None,
        description='Whether the client anticipates a significant expense increase.',
    )
    anticipateIncomeDecrease: AnticipateIncomeDecrease | None = Field(
        None,
        description='Whether the client anticipates an income decrease (e.g., retirement).',
    )
    anticipateLiquidAssetDecrease: AnticipateLiquidAssetDecrease | None = Field(
        None, description='Whether the client anticipates a decrease in liquid assets.'
    )
    financialObjectives: str | None = Field(
        None,
        description="Client's stated financial goals and objectives.",
        examples=[
            'Supplement Social Security with guaranteed income; preserve assets for estate'
        ],
    )
    distributionPlan: str | None = Field(
        None,
        description='Planned distribution or withdrawal strategy.',
        examples=['Systematic withdrawals beginning at age 67'],
    )
    ownedAssets: str | None = Field(
        None,
        description='Summary of major owned assets.',
        examples=[
            'Primary residence (paid off), 401(k), Roth IRA, existing fixed annuity'
        ],
    )
    timeToFirstDistribution: str | None = Field(
        None,
        description='Expected time until the first distribution from the annuity.',
        examples=['5 years'],
    )
    expectedHoldingPeriod: str | None = Field(
        None,
        description='Expected total holding period for the annuity.',
        examples=['10+ years'],
    )
    sourceOfFunds: str | None = Field(
        None,
        description='Source of funds for the annuity purchase.',
        examples=['1035 exchange from existing annuity and savings account'],
    )
    employmentStatus: str | None = Field(
        None,
        description='Current employment status and retirement plans.',
        examples=['Employed full-time, plans to retire in 5 years'],
    )
    applyToMeansTestedBenefits: ApplyToMeansTestedBenefits | None = Field(
        None,
        description='Whether the client expects to apply for means-tested government benefits.',
    )


class SuitabilityInlineData(BaseModel):
    clientObjectives: str = Field(
        ..., description="Summary of the client's stated financial objectives."
    )
    riskTolerance: str = Field(
        ..., description="Client's self-assessed risk tolerance level."
    )
    timeHorizon: str = Field(..., description='Expected investment time horizon.')
    liquidityNeeds: str = Field(
        ..., description="Assessment of the client's need for accessible funds."
    )
    taxConsiderations: str = Field(
        ..., description='Relevant tax situation and planning considerations.'
    )
    guaranteedIncome: str = Field(
        ..., description="Client's desired guaranteed income provisions."
    )
    rateExpectations: str = Field(
        ..., description="Client's rate and return expectations or preferences."
    )
    surrenderTimeline: str = Field(
        ...,
        description='Whether or when the client anticipates surrendering the contract.',
    )
    livingBenefits: list[str] = Field(
        ..., description='Living benefit features important to the client.'
    )
    advisorEligibility: str | None = Field(
        None,
        description='Advisor licensing and appointment status relevant to the assessment.',
    )
    score: int | None = Field(None, description='Composite suitability score (0-100).')
    isPrefilled: bool | None = Field(
        None, description='Whether the assessment was pre-populated from existing data.'
    )


class PolicyFeaturesData(BaseModel):
    surrenderCharge: str | None = Field(
        None,
        description='Current surrender charge percentage and schedule position.',
        examples=['2.5% (Year 7 of 10)'],
    )
    withdrawalAllowance: str | None = Field(
        None,
        description='Penalty-free withdrawal provision.',
        examples=['10% annually penalty-free'],
    )
    mvaPenalty: str | None = Field(
        None,
        description='Current market value adjustment impact if surrendered today.',
        examples=['-3.8% if surrendered today'],
    )
    rateGuarantee: str | None = Field(
        None,
        description='Remaining duration of the current rate guarantee period.',
        examples=['5 years remaining'],
    )
    features: list[PolicyFeature] | None = Field(
        None, description='Product features included with the contract.'
    )
    benefits: list[PolicyFeature] | None = Field(
        None, description='Contractual benefits provided by the policy.'
    )
    riders: list[PolicyFeature] | None = Field(
        None, description='Optional riders attached to the policy.'
    )
    limitations: list[PolicyFeature] | None = Field(
        None, description='Contractual restrictions and limitations.'
    )


class VisualizationProduct(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    productId: str = Field(
        ...,
        description='Business identifier for the product.',
        examples=['PROD-FLEX-MYGA-7'],
    )
    name: str = Field(
        ..., description='Product marketing name.', examples=['FlexGrowth Plus MYGA']
    )
    carrier: str = Field(
        ..., description='Issuing insurance carrier.', examples=['Great American']
    )
    currentRate: float = Field(
        ...,
        description='Current credited interest rate as a decimal percentage.',
        examples=[4.25],
    )
    guaranteedMinRate: float = Field(
        ...,
        description='Contractual guaranteed minimum rate as a decimal percentage.',
        examples=[2.5],
    )
    surrenderYears: int = Field(
        ..., description='Number of years in the surrender charge period.', examples=[7]
    )
    initialValue: float = Field(
        ...,
        description='Starting contract value used for projections.',
        examples=[100000],
    )
    premiumBonus: float | None = Field(
        None,
        description='First-year premium bonus as a decimal percentage.',
        examples=[3.0],
    )
    incomeScore: conint(ge=0, le=100) = Field(
        ..., description='Relative income generation score (0-100).', examples=[72]
    )
    growthScore: conint(ge=0, le=100) = Field(
        ..., description='Relative growth potential score (0-100).', examples=[85]
    )
    liquidityScore: conint(ge=0, le=100) = Field(
        ..., description='Relative liquidity and access score (0-100).', examples=[45]
    )
    protectionScore: conint(ge=0, le=100) = Field(
        ..., description='Relative downside protection score (0-100).', examples=[88]
    )
    projectedRates: list[ProjectedRate] = Field(
        ..., description='Multi-scenario rate projections across the contract life.'
    )
    performanceData: list[PerformanceDataPoint] = Field(
        ..., description='Projected account value and income over time.'
    )
    features: list[VisualizationFeature] = Field(
        ...,
        description='Time-bounded product feature windows for timeline visualization.',
    )


class ClientProfile(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    clientId: str = Field(
        ...,
        description='Business identifier for the client.',
        examples=['CLT-2024-00412'],
    )
    clientName: str = Field(
        ..., description='Full name of the client.', examples=['Margaret A. Whitfield']
    )
    parameters: ComparisonParameters
    suitability: SuitabilityInlineData | None = Field(
        None, description='Suitability assessment data for this client, if available.'
    )


class PolicyData(BaseModel):
    ID: str = Field(
        ..., description='Internal record identifier (base64-encoded UUID).'
    )
    clientId: str = Field(
        ...,
        description='Business identifier for the client who owns this policy.',
        examples=['CLT-2024-00100'],
    )
    contractId: str = Field(
        ...,
        description='Carrier-assigned contract or policy number.',
        examples=['ANN-2020-5621'],
    )
    clientName: str = Field(
        ...,
        description='Full name of the policy owner.',
        examples=['Margaret A. Whitfield'],
    )
    carrier: str = Field(
        ...,
        description='Issuing insurance carrier.',
        examples=['Integrity Life Insurance'],
    )
    productName: str = Field(
        ...,
        description='Name of the annuity product.',
        examples=['SecureChoice Multi-Year Guarantee Annuity'],
    )
    issueDate: str = Field(
        ..., description='Date the contract was issued.', examples=['03/15/2018']
    )
    currentValue: str = Field(
        ...,
        description='Current accumulated contract value, formatted with currency symbol.',
        examples=['$180,000'],
    )
    surrenderValue: str = Field(
        ...,
        description='Current cash surrender value after applicable charges.',
        examples=['$176,400'],
    )
    currentRate: str = Field(
        ..., description='Interest rate currently being credited.', examples=['3.80%']
    )
    renewalRate: str = Field(
        ...,
        description='Rate that will apply at the next renewal period.',
        examples=['1.50%'],
    )
    guaranteedMinRate: str = Field(
        ...,
        description='Contractual guaranteed minimum interest rate.',
        examples=['1.50%'],
    )
    renewalDate: str = Field(
        ..., description='Date of the next rate renewal.', examples=['03/15/2026']
    )
    isMinRateRenewal: bool = Field(
        ..., description='Whether the renewal rate equals the guaranteed minimum.'
    )
    suitabilityStatus: SuitabilityStatus = Field(
        ..., description='Current state of the suitability review for this policy.'
    )
    eligibilityStatus: EligibilityStatus = Field(
        ...,
        description='Whether the policy is eligible for renewal or exchange activity.',
    )
    features: PolicyFeaturesData
