"""
Regenerate agents/iri_schemas.py from agents/iri_api_spec.yaml (OpenAPI 3.0.3).

OpenAPI is the source of truth for IRI API shapes. Run this after editing the spec:

  pip install 'datamodel-code-generator[http]'
  PYTHONPATH=. python -m agents.regenerate_iri_schemas

Then fix the generated file header to point to this script and run any tests.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

AGENTS_DIR = Path(__file__).resolve().parent
SPEC = AGENTS_DIR / "iri_api_spec.yaml"
OUTPUT = AGENTS_DIR / "iri_schemas.py"


def main() -> int:
    if not SPEC.exists():
        print(f"Spec not found: {SPEC}", file=sys.stderr)
        return 1
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(SPEC),
            "--input-file-type",
            "openapi",
            "--output",
            str(OUTPUT),
            "--output-model-type",
            "pydantic_v2.BaseModel",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        return result.returncode
    # Prepend "do not edit" header
    content = OUTPUT.read_text()
    header = '''# DO NOT EDIT BY HAND.
# Generated from agents/iri_api_spec.yaml (OpenAPI 3.0.3).
# Regenerate with: python -m agents.regenerate_iri_schemas
#
'''
    if not content.lstrip().startswith("# generated by datamodel-code-generator"):
        # Generator may have written a different header; still prepend our notice
        content = header + content
    else:
        content = header + content.lstrip()
    OUTPUT.write_text(content)
    print(f"Regenerated {OUTPUT} from {SPEC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
