# DO NOT EDIT BY HAND.
# Generated from agents/iri_api_spec.yaml (OpenAPI 3.0.3).
# Regenerate with: python -m agents.regenerate_iri_schemas
#
# generated by datamodel-codegen:
#   filename:  iri_api_spec.yaml
#   timestamp: 2026-02-24T18:41:44+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AlertType(Enum):
    replacement_recommended = 'replacement_recommended'
    replacement_opportunity = 'replacement_opportunity'
    missing_info = 'missing_info'
    suitability_review = 'suitability_review'
    income_planning = 'income_planning'


class Priority(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class Status(Enum):
    pending = 'pending'
    reviewed = 'reviewed'
    snoozed = 'snoozed'
    dismissed = 'dismissed'


class RenewalAlert(BaseModel):
    id: str = Field(..., examples=['alert-ANN-2020-5621-renewal'])
    clientId: str = Field(..., examples=['CLI-1001'])
    policyId: str = Field(..., examples=['ANN-2020-5621'])
    clientName: str = Field(..., examples=['Maria Rodriguez'])
    carrier: str = Field(..., examples=['Athene'])
    renewalDate: str = Field(..., examples=['15 Days'])
    daysUntilRenewal: int = Field(..., examples=[15])
    currentRate: str = Field(..., examples=['3.8%'])
    renewalRate: str = Field(..., examples=['1.5%'])
    currentValue: str = Field(..., examples=['$180,000'])
    isMinRate: bool = Field(..., examples=[True])
    priority: Priority
    hasDataException: bool
    missingFields: list[str] | None = None
    status: Status
    alertType: AlertType
    alertTypes: list[AlertType] | None = None
    alertDescription: str


class DashboardStats(BaseModel):
    total: int = Field(..., examples=[10])
    high: int = Field(..., examples=[3])
    urgent: int = Field(..., examples=[4])
    totalValue: float = Field(..., examples=[1839000])


class SuitabilityStatus(Enum):
    complete = 'complete'
    incomplete = 'incomplete'
    not_started = 'not-started'


class EligibilityStatus(Enum):
    eligible = 'eligible'
    restricted = 'restricted'
    ineligible = 'ineligible'


class Type(Enum):
    feature = 'feature'
    benefit = 'benefit'
    rider = 'rider'
    limitation = 'limitation'


class PolicyFeature(BaseModel):
    name: str
    description: str
    included: bool
    type: Type


class SuitabilityScore(BaseModel):
    score: int = Field(..., examples=[85])
    reasoning: list[str]
    complianceNotes: list[str]
    missingData: list[str]


class SuitabilityData(BaseModel):
    clientObjectives: str
    riskTolerance: str
    timeHorizon: str
    liquidityNeeds: str
    taxConsiderations: str
    guaranteedIncome: str
    rateExpectations: str
    surrenderTimeline: str
    livingBenefits: list[str]
    advisorEligibility: str
    score: int
    isPrefilled: bool


class DisclosureItem(BaseModel):
    id: str
    label: str | None = None
    title: str | None = None
    description: str | None = None
    documentName: str | None = None
    required: bool
    link: str | None = None


class Type1(Enum):
    renew = 'renew'
    replace = 'replace'


class TransactionOption(BaseModel):
    type: Type1
    label: str
    description: str
    requirements: list[str]
    warnings: list[str] | None = None
    isAvailable: bool
    unavailableReason: str | None = None
    pros: list[str] | None = None
    cons: list[str] | None = None


class AuditLogEntry(BaseModel):
    timestamp: str
    user: str
    action: str
    details: str


class ProductOption(BaseModel):
    name: str = Field(..., examples=['FlexGrowth Plus MYGA'])
    carrier: str = Field(..., examples=['Great American'])
    rate: str = Field(..., examples=['4.25%'])
    term: str = Field(..., examples=['7 years'])
    premiumBonus: str | None = Field(None, examples=['3.0%'])
    surrenderPeriod: str = Field(..., examples=['7'])
    surrenderCharge: str | None = Field(None, examples=['7% (declining)'])
    freeWithdrawal: str = Field(..., examples=['10%'])
    deathBenefit: str = Field(..., examples=['Enhanced'])
    guaranteedMinRate: str = Field(..., examples=['2.50%'])
    riders: list[str] | None = None
    features: list[str] | None = None
    liquidity: str | None = None
    mvaPenalty: str | None = None
    licensingApproved: bool | None = None
    licensingDetails: str | None = None


class ResidesInNursingHome(Enum):
    yes = 'yes'
    no = 'no'


class HasLongTermCareInsurance(Enum):
    yes = 'yes'
    no = 'no'


class HasMedicareSupplemental(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateExpenseIncrease(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateIncomeDecrease(Enum):
    yes = 'yes'
    no = 'no'


class AnticipateLiquidAssetDecrease(Enum):
    yes = 'yes'
    no = 'no'


class ApplyToMeansTestedBenefits(Enum):
    yes = 'yes'
    no = 'no'


class ComparisonParameters(BaseModel):
    residesInNursingHome: ResidesInNursingHome | None = None
    hasLongTermCareInsurance: HasLongTermCareInsurance | None = None
    hasMedicareSupplemental: HasMedicareSupplemental | None = None
    grossIncome: str | None = Field(None, examples=['85000'])
    disposableIncome: str | None = Field(None, examples=['45000'])
    taxBracket: str | None = Field(None, examples=['22%'])
    householdLiquidAssets: str | None = Field(None, examples=['250000'])
    monthlyLivingExpenses: str | None = Field(None, examples=['4500'])
    totalAnnuityValue: str | None = Field(None, examples=['180000'])
    householdNetWorth: str | None = Field(None, examples=['650000'])
    anticipateExpenseIncrease: AnticipateExpenseIncrease | None = None
    anticipateIncomeDecrease: AnticipateIncomeDecrease | None = None
    anticipateLiquidAssetDecrease: AnticipateLiquidAssetDecrease | None = None
    financialObjectives: str | None = None
    distributionPlan: str | None = None
    ownedAssets: str | None = None
    timeToFirstDistribution: str | None = None
    expectedHoldingPeriod: str | None = None
    sourceOfFunds: str | None = None
    employmentStatus: str | None = None
    applyToMeansTestedBenefits: ApplyToMeansTestedBenefits | None = None


class TransactionType(Enum):
    renew = 'renew'
    replace = 'replace'


class NigoIssue(BaseModel):
    issue: str | None = None
    remediation: str | None = None
    resolved: bool | None = None


class Status1(Enum):
    received = 'received'
    in_review = 'in-review'
    nigo = 'nigo'
    approved = 'approved'
    issued = 'issued'


class SubmissionStatus(BaseModel):
    status: Status1
    timestamp: str
    notes: str | None = None


class Error(BaseModel):
    error: str = Field(..., examples=['NOT_FOUND'])
    message: str = Field(..., examples=['Alert not found'])
    details: dict[str, Any] | None = None


class PolicyFeaturesData(BaseModel):
    features: list[PolicyFeature] | None = None
    benefits: list[PolicyFeature] | None = None
    riders: list[PolicyFeature] | None = None
    limitations: list[PolicyFeature] | None = None
    surrenderCharge: str | None = Field(None, examples=['2.5% (Year 7 of 10)'])
    withdrawalAllowance: str | None = Field(
        None, examples=['10% annually penalty-free']
    )
    mvaPenalty: str | None = Field(None, examples=['-3.8% if surrendered today'])
    rateGuarantee: str | None = Field(None, examples=['5 years remaining'])


class ComparisonData(BaseModel):
    current: ProductOption
    alternatives: list[ProductOption]
    missingData: bool


class ClientProfile(BaseModel):
    clientId: str
    clientName: str
    parameters: ComparisonParameters


class SubmissionData(BaseModel):
    submissionId: str = Field(..., examples=['SUB-2026-1234'])
    submittedDate: str
    carrier: str
    transactionType: TransactionType
    currentStatus: SubmissionStatus
    statusHistory: list[SubmissionStatus]
    nigoIssues: list[NigoIssue] | None = None


class PolicyData(BaseModel):
    contractId: str = Field(..., examples=['ANN-2020-5621'])
    clientName: str
    carrier: str
    productName: str = Field(
        ..., examples=['SecureChoice Multi-Year Guarantee Annuity']
    )
    issueDate: str = Field(..., examples=['03/15/2018'])
    currentValue: str = Field(..., examples=['$180,000'])
    surrenderValue: str = Field(..., examples=['$176,400'])
    currentRate: str = Field(..., examples=['3.8%'])
    renewalRate: str = Field(..., examples=['1.5%'])
    guaranteedMinRate: str = Field(..., examples=['1.50%'])
    renewalDate: str
    isMinRateRenewal: bool
    suitabilityStatus: SuitabilityStatus
    eligibilityStatus: EligibilityStatus
    features: PolicyFeaturesData


class ComparisonResult(BaseModel):
    comparisonData: ComparisonData


class AlertDetail(BaseModel):
    alert: RenewalAlert
    clientAlerts: list[RenewalAlert] = Field(
        ..., description='All alerts for this client (for grouped review)'
    )
    policyData: PolicyData
    aiSuitabilityScore: SuitabilityScore
    suitabilityData: SuitabilityData
    disclosureItems: list[DisclosureItem]
    transactionOptions: list[TransactionOption]
    auditLog: list[AuditLogEntry]
